### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by Borwe**
Add windows support, and a simple starting point to add support for other servers..
Current servers that have been added support:

1. Angular
2. Dockerfile
3. Lua
4. Python
5. Vim
6. Cpp
7. Cmake
8. Java

LspInstall only pops hints for those that have an install script, when on windows.

### CODE REVIEW

**Comment by Borwe** [comment]
Java ported to work on Windows also.

**Comment by TeoDev1611** [comment]
What happened with this?

**Comment by Borwe** [comment]
Included cmake support

**Comment by Borwe** [comment]
Closing, migrated to vim.

**Pull request closed without merging**
