### PR TITLE
Added support for omnisharp

### PR DESCRIPTION
**Pull request by MordechaiHadad**
Configuring the cmd array for omnisharp's lspconfig is pretty weird so the syntax I used is a bit different compared to the usual one.
But it works.

### CODE REVIEW

**Comment by kabouzeid** [comment]
thanks! for what language is this?

**Comment by MordechaiHadad** [comment]
> 
> 
> thanks! for what language is this?

Both c# and visual basic

**Comment by kabouzeid** [comment]
Usually I name the configs after the language.
e.g. `LspInstall python` installs `pyright` and `LspInstall lua` installs `sumneko-lua language server`.

If it's the defacto standard C# lang server I would call it `csharp`
If it's instead the defacto standard .NET lang server I would call it `dotnet` or `omnisharp`
Otherwise I would call it `omnisharp`.

What do you say?

**Comment by MordechaiHadad** [comment]
> 
> 
> Usually I name the configs after the language.
> e.g. `LspInstall python` installs `pyright` and `LspInstall lua` installs `sumneko-lua language server`.
> 
> If it's the defacto standard C# lang server I would call it `csharp`
> If it's instead the defacto standard .NET lang server I would call it `dotnet` or `omnisharp`
> Otherwise I would call it `omnisharp`.
> 
> What do you say?

i think dotnet is better for this case
omnisharp is just the lsp server
dotnet is both csharp and visual basic

**Comment by kabouzeid** [comment]
Can omnisharp be used for C# even when dotnet is not used?

**Comment by MordechaiHadad** [comment]
> 
> 
> Can omnisharp be used for C# even when dotnet is not used?

as far as i know yes

**Comment by MordechaiHadad** [comment]
> 
> 
> Can omnisharp be used for C# even when dotnet is not used?

wait I think I misunderstood the message

C# and VB are part of dotnet

**Comment by kabouzeid** [comment]
Alright, I think we should call it `csharp` then. The official VSCode extension is also called C# and uses OmniSharp.

I didn't even know Visual Basic is still a thing 😅

Thanks for your work, will merge this soon!

**Comment by MordechaiHadad** [comment]
> 
> 
> Alright, I think we should call it `csharp` then. The official VSCode extension is also called C# and uses OmniSharp.
> 
> I didn't even know Visual Basic is still a thing 😅
> 
> Thanks for your work, will merge this soon!

thank you i will change the naming

**Comment by kabouzeid** [comment]
Thanks again :)

**Pull request merged**
