### PR TITLE
Add jedi-language-server

### PR DESCRIPTION
**Pull request by dirn**
This makes the [jedi-language-server][jedi] installable.

[jedi]: https://github.com/pappasam/jedi-language-server

### CODE REVIEW

**Comment by kabouzeid** [comment]
Thanks! Not sure about `jedi` though. Why would you use it over `pyright`?

**Comment by dirn** [comment]
The short answer: I use mypy.

The long answer: I find pyright very confusing. It seems to be both a static type checker and a language server. I tried it briefly (via coc.nvim) and found its diagnostics to be distracting because there didn't appear to be a way to disable 100% of its type-related messages. I settled on jedi-language-server for things like code navigation and refactoring coupled with diagnostic-language-server for running linters (e.g., mypy) and formatters.

**Comment by kabouzeid** [comment]
Makes sense. Any reason why you didn't go with https://github.com/palantir/python-language-server ?

**Comment by dirn** [comment]
>The base language server requires Jedi to provide Completions, Definitions, Hover, References, Signature Help, and Symbols

At that point, why wouldn’t I just use Jedi?

**Comment by kabouzeid** [comment]
Aren't both of them just bridges to expose jedi's functionality through the LSP protocol?

**Comment by dirn** [comment]
I’ve been happy using jedi-language-server and have no plans to switch to another one. If this project wants to support a subset of the servers supported by [lspconfig](https://github.com/neovim/nvim-lspconfig), I’m happy to keep this in my personal configuration, but since that project recommends this one I figured the goal was more parity.

**Review by dirn — COMMENTED** [review]
Will this break the [advanced configuration](https://github.com/kabouzeid/nvim-lspinstall#advanced-configuration-recommended)?

```local servers = require'lspinstall'.installed_servers()
for _, server in pairs(servers) do
  require'lspconfig'[server].setup{}
end```

**Comment by kabouzeid** [comment]
Closing this for now because we already have pyright.

For those of you that want jedi, just add this to your config before you call setup:

```lua
local jedi_config = require"lspinstall/util".extract_config("jedi_language_server") 
jedi_config.default_config.cmd[1] = "./venv/bin/jedi-language-server"

require'lspinstall/servers'.jedi = vim.tbl_extend('error', jedi_config, {
  install_script = [[
  python3 -m venv ./venv
  ./venv/bin/pip3 install --upgrade pip
  ./venv/bin/pip3 install --upgrade jedi-language-server
  ]]
})
```

**Pull request closed without merging**
