### PR TITLE
lazy require servers

### PR DESCRIPTION
**Pull request by lewis6991**

### CODE REVIEW

**Comment by kabouzeid** [comment]
Does not work. eg pairs() doesn't work anymore.

**Comment by lewis6991** [comment]
Was it necessary to close the PR? Comes across a little dismissive.

I'm sure I'll be able to work on the PR some more so it does work.

**Comment by kabouzeid** [comment]
I'm sorry, I meant no offense! Feel free to reopen/recreate if you find something :)
I've just spent 30 mins trying various approaches, but none of them checked all the boxes. I don't want to introduce unstable/confusing behavior for such a minor performance gain.

**Comment by lewis6991** [comment]
No worries, just opened #175

**Pull request closed without merging**
